language: ruby

rvm:
    - 2.2.6

services:
  - postgresql

before_script:
  - psql -c 'create database tubecam_test;' -U postgres

# deploy:
#  provider: heroku
#  api_key:
#    secure: "af9d2e25-d5bd-4da4-be05-d3037524db82"
